"""add embedding identities and vector indexes

Revision ID: 0188f7ab7055
Revises: e8ed66902805
Create Date: 2026-08-10 04:10:07.011186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0188f7ab7055'
down_revision: Union[str, Sequence[str], None] = 'e8ed66902805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_embedding_identity_fingerprint'),
    sa.UniqueConstraint('id', 'profile_name', name='uq_embedding_identity_id_profile')
    )
    op.create_index(op.f('ix_embedding_identities_profile_name'), 'embedding_identities', ['profile_name'], unique=False)
    op.create_table('vector_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('embedding_identity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('building', 'ready', 'active', 'deprecated', 'failed', name='vector_index_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_identity_id', 'profile_name'], ['embedding_identities.id', 'embedding_identities.profile_name'], name='fk_vector_index_embedding_identity_profile', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_indexes_organization_id'), 'vector_indexes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vector_indexes_profile_name'), 'vector_indexes', ['profile_name'], unique=False)
    op.create_index('uq_active_vector_index_per_org_profile', 'vector_indexes', ['organization_id', 'profile_name'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_vector_index_per_org_profile', table_name='vector_indexes', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_vector_indexes_profile_name'), table_name='vector_indexes')
    op.drop_index(op.f('ix_vector_indexes_organization_id'), table_name='vector_indexes')
    op.drop_table('vector_indexes')
    op.drop_index(op.f('ix_embedding_identities_profile_name'), table_name='embedding_identities')
    op.drop_table('embedding_identities')
    # ### end Alembic commands ###
