"""add page number to document chunks

Revision ID: 65073d68f1d6
Revises: 0a198bd69345
Create Date: 2026-08-09 20:29:03.155756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65073d68f1d6'
down_revision: Union[str, Sequence[str], None] = '0a198bd69345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_chunks',
        sa.Column(
            'page_number',
            sa.Integer(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE document_chunks SET page_number = 1 "
        "WHERE page_number IS NULL"
    )

    op.alter_column(
        'document_chunks',
        'page_number',
        existing_type=sa.Integer(),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
